// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class InvoiceDetail
{
    public int LineNo { get; set; }

    public string ProductName { get; set; }

    public int UnitNo { get; set; }

    public decimal Price { get; set; }

    public decimal Quantity { get; set; }

    public decimal Total { get; set; }

    public DateTime ExpiryDate { get; set; }

    public virtual Unit UnitNoNavigation { get; set; }
}